'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.6413
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Modulo_MaterialesCentral.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1rightarrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1rightarrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1rightarrow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1rightarrow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Acercade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Acercade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ActualizacionesInstaladas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActualizacionesInstaladas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actualizar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actualizar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Agregar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Agregar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AsignarMaterial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AsignarMaterial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Atencion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Atencion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Baja() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Baja", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BajaReing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BajaReing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Buscar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Buscar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BuscarUpdates() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuscarUpdates", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cancelar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cancelar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CancelarOrden() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CancelarOrden", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cerrar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cerrar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property conectar_bdd2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("conectar bdd2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property consultaAlertas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultaAlertas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property documento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("documento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Earth_Download_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Earth-Download-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Editar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Editar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ErrorSistema2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ErrorSistema2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ErrorSistemaGrande() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ErrorSistemaGrande", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Exportar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exportar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fallaSistema() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fallaSistema", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property greenled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greenled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Guardar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guardar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Guardias() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guardias", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HoraNo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HoraNo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HoraSi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HoraSi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Imprimir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Imprimir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LogoSIAC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoSIAC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logout24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mail_Enviado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mail_Enviado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mail_replay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_replay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mat_AsignarMensajero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mat_AsignarMensajero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mat_CancelarMensajero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mat_CancelarMensajero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mat_ValidarMensajero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mat_ValidarMensajero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MaterialesCancelar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaterialesCancelar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MaterialesInventario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaterialesInventario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MaterialesRotular() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaterialesRotular", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MaterialesValidar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaterialesValidar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OrdenCompra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OrdenCompra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ordenTrabajo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ordenTrabajo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Proveedores() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Proveedores", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rastreo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rastreo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ReporteFalla() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReporteFalla", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property security_blue1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("security blue1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property security_blue2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("security blue2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property security_blue3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("security blue3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property seguimientoFallas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seguimientoFallas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property solicitudEquipo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("solicitudEquipo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SurtirSolicitud() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SurtirSolicitud", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property users_business() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users_business", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ValidarCompra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ValidarCompra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ValidarSolicitud() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ValidarSolicitud", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
